[book]
authors = ["Jose Catala"]
language = "en"
multilingual = false
src = "src"
title = "ShootingDApp Documentation"

[output.html]
git-repository-url = "https://github.com/JFCaBa/shooting-game-docs"
edit-url-template = "https://github.com/JFCaBa/shooting-game-docs/edit/main/{path}"
site-url = "/shooting-game-docs/"
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]

[output.html.playpen]
editable = true
copy-js = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.mermaid]
command = "mdbook-mermaid"